In [1]:
def bitReverse(x, log2n):
    n = 0
    for i in range(log2n):
        n <<= 1
        n |= (x & 1)
        x >>= 1
    return n

In [15]:
def bit_reverse(x, width):
    b = '{:0{width}b}'.format(x, width=width)
    return int(b[::-1], 2)

In [16]:
import math
import numpy as np

In [63]:
def bit_reversal(x: np.ndarray) -> np.ndarray:
    N = len(x)
    width = int(math.log2(N))
    for i in range(N):
        reverse_i = bit_reverse(i, width)
        if i < reverse_i:
            x[i], x[reverse_i] = x[reverse_i], x[i]
    return x

In [81]:
def bit_reversal2(x):
    N = len(x)
    width = int(math.log2(N))
    for i in range(N):
        reverse_i = bit_reverse(i, width)
        if i < reverse_i:
            x[i], x[reverse_i] = x[reverse_i], x[i]

    return x

In [82]:
bit_reversal2(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]))

array([ 0,  8,  4, 12,  2, 10,  6, 14,  1,  9,  5, 13,  3, 11,  7, 15])

array([ 0,  8,  4, 12,  2, 10,  6, 14,  1,  9,  5, 13,  3, 11,  7, 15])
array([ 0,  8,  4, 12,  2, 10,  6, 14,  1,  9,  5, 11,  3, 13,  7, 15])

In [22]:
def fft(x: np.ndarray) -> np.ndarray:bit_reverse(x[i], width)
    N = len(x)

    if N <= 1:
        return x

    pad_len = (2 ** math.floor(math.log2(N) + 1)) - N
    if pad_len != N:
        x = np.concatenate((x, np.zeros(pad_len)))

    newN = len(x)
    x = bit_reversal(x)
    for s in range(1, int(math.log2(newN)) + 1):
        M = 2**s
        WM = np.exp(-2j * np.pi / M)
        for l in range(0, newN - M, M):
            W = 1
            for k in range(M//2 - 1):
                g = x[l + k]
                h = W * x[l + k + M//2]
                x[l + k] = g + h
                x[l + k + M//2] = g - h
                W = W * WM

    return x

In [23]:
fft(np.array([0, 1, 2, 3, 4, 5, 6, 7]))

array([ 2,  4, -2,  6,  1,  5,  3,  7])

In [24]:
np.fft.fft(np.array([0, 1, 2, 3, 4, 5, 6, 7]))

array([28.+0.j        , -4.+9.65685425j, -4.+4.j        , -4.+1.65685425j,
       -4.+0.j        , -4.-1.65685425j, -4.-4.j        , -4.-9.65685425j])

In [28]:
np.exp(-2j)

np.complex128(-0.4161468365471424-0.9092974268256817j)